[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = [
    "nameko_sqlalchemy/",
    "test/",
]
known_first_party = "nameko_chassis"

[tool.ruff]
extend-exclude = [
    ".venv",
    "migrations",
]
ignore = [
    "E402",
    "E501",
]
select = [
    "E",
    "F",
    "W",
]

[tool.mypy]
python_version = "3.10"
plugins = "sqlalchemy.ext.mypy.plugin"
mypy_path = "nameko_sqlalchemy/"
namespace_packages = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
warn_redundant_casts = true

ignore_missing_imports = true

[tool.pytest.ini_options]
norecursedirs = [".git", ".tox", "dist", "build"]
testpaths = ["test"]